version: '2'
services:
  angular:
    image: hebertcb/websalud-frontend:v1
    container_name: angular-frontend
    networks:
      - frontend
    ports:
      - "8080:80"

  express:
    image: hebertcb/websalud-api:v1
    container_name: express-api
    networks:
      - frontend
      - backend
    ports:
      - "3000:3000"

  database:
    image: hebertcb/websalud-db:v1
    container_name: mysql-bd
    environment:
      - MYSQL_ROOT_PASSWORD=12345
    networks:
      - backend
    ports:
      - "3306:3306"

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
